import type { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import AuthWrapper from "../(auth)/AuthWrapper";
import NavigationBar from "@/components/design/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookieHeader = cookieStore.toString();
  console.log(cookieStore);



  // Call your Express API to check the user
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/auth/me`, {
    headers: { cookie: cookieHeader },
    cache: "no-store", // Ensure fresh data on every request
  });

  // If not authenticated, redirect to login.
  if (!res.ok) {
    redirect("/sign-in");
  }

  // Parse the user data
  const data = await res.json();
  console.log(data);
  return (
  
        <AuthWrapper userFromServer={data}>
            <NavigationBar />
          {children}
        </AuthWrapper>
      
  );
}
